### ISSUE TITLE
Doesn't work with lombok annotation processor

### ISSUE THREAD

**Issue by CertainLach** [SpongePowered/MixinGradle#11]
When i try to add lombok annotation processor to my mixin plugin via
```
annotationProcessor 'org.projectlombok:lombok:1.18.6'
```
I see no refmap in output jar

**Comment by gabizou** [comment]
Kinda need some more information about your setup. What isn't working precisely? What version of MixinGradle? What version of Gradle? Do you have a `build.gradle` handy to refer to to reproduce the issue? Is there any exception or stack trace printed out during the build log?

**Comment by CertainLach** [comment]
Gradle 4.10.3 (Using wrapper), mixingradle 0.6-SNAPSHOT
build.gradle: https://bin.0la.ch/acidolohek.cs
Building project with this config (`./gradlew clean build`) getting correct, working mod
![изображение](https://user-images.githubusercontent.com/6235312/57527222-a8e61000-7348-11e9-9062-6908c1d65fdf.png)
But, if i uncomment line 54 (`annotationProcessor 'org.projectlombok:lombok:1.18.6'`), and rebuild project (`./gradlew clean build` again), i'm getting the following:
![изображение](https://user-images.githubusercontent.com/6235312/57527395-f95d6d80-7348-11e9-988b-df8846dd6ba3.png)
(Refmap is missing)
There is nothing wrong in console, output is same

**Comment by Beshelmek** [comment]
Same issue

**Comment by qlow** [comment]
Any updates on this? Still doesn't work with MixinGradle 0.6-SNAPSHOT

**Comment by minemalox** [comment]
Same on MixinGradle 0.7-SNAPSHOT

**Comment by qlow** [comment]
> Same on MixinGradle 0.7-SNAPSHOT

Here you have the solution:
https://github.com/SpongePowered/Mixin/issues/404
