### ISSUE TITLE
Gradle 5 breaking plugin

### ISSUE THREAD

**Issue by RDIL** [SpongePowered/MixinGradle#12]
Changing to gradle 5 adds error in my project; it says the plugin can’t be found (I do have version specified).

**Comment by gabizou** [comment]
We're already in the [process of updating MixinGradle] to be compatible with newer versions of Gradle. For ForgeGradle 2.x projects, it's highly recommended to use Gradle 4.10.3 at the latest as Gradle 5 introduces several changes that broke compatibility with previous versions of Gradle.
