### ISSUE TITLE
SimpleFileCollection has been removed

### ISSUE THREAD

**Issue by RDIL** [SpongePowered/MixinGradle#13]
The SimpleFileCollection type has been removed as of gradle 5.

Gradle build scan says:

```groovy
Please use Project.files() instead.
Used in: mixingradle - 'MixinExtension.groovy:24'
```

cc @Mumfrey

**Comment by gabizou** [comment]
Old versions of MixinGradle will not be updated for newer versions of Gradle, much like how ForgeGradle 2.x is not compatible with Gradle 5. MixinGradle has a lot of work to take place to support the new FG3.x pipelines, which also introduces Gradle 5.x support, as such, going to close this issue as it's just going to be unsupported trying to run newer Gradle than what the tools are built against.
