### ISSUE TITLE
MixinGradle and Kotlin support

### ISSUE THREAD

**Issue by Ivasik78** [SpongePowered/MixinGradle#14]
Hello, I have projects that use mixin and also they are written in kotlin and I noticed that it doesn't work together. Judging by the code in JavaCompile, the task is given arguments, just as you can do with Kapt, but idk why hasn't it been done yet :/
[Kapt](https://kotlinlang.org/docs/reference/kapt.html)

**Comment by gabizou** [comment]
MixinGradle only passes around configuring options for the Mixin AP, Kotlin support is more directly related to https://github.com/SpongePowered/Mixin/issues/245 itself and not MixinGradle. 

Explaining further the [shortcomings of trying to write Mixins with Kotlin](https://github.com/SpongePowered/Mixin/issues/245#issuecomment-397858393), it's best honestly to write the actual mixins in Java and if you really need to, the implementation in Kotlin.
