### ISSUE TITLE
No refmap.json gets generated when putting mixins under src/main/scala

### ISSUE THREAD

**Issue by LolHens** [SpongePowered/MixinGradle#19]
I am trying to use mixins (java classes) in a scala mod but I am running into problems where the refmap file is not generated if I put the mixins under src/main/scala. If I put them into src/main/java it works but then I cannot call stuff from src/main/scala from my mixins. Since I am already using this project layout on fabric I thought it might also work for forge with MixinGradle. Mabe there is a workaround for this.
EDIT: well, I think I have a not-so-great solution but at least it's a solution. Will post this here once I've automated and verified it.
EDIT:
yes I know this is not the best solution and pretty convoluted but here it is:
[java-mixin-stubber](https://github.com/LolHens/java-mixin-stubber/blob/master/src/main/scala/de/lolhens/jstubber/Stubber.java) is a java source code transformer that drops the method bodies and imports that might reference anything in src/main/scala.
```gradle
buildscript {
    dependencies {
        classpath 'de.lolhens:java-mixin-stubber:0.0.2'
    }
}

def mixinstubsDir = file("$compileJava.temporaryDir/mixinstubs")

sourceSets.main.java.srcDirs += mixinstubsDir

def mixinstubs = task('mixinstubs') {
    doLast {
        delete(mixinstubsDir)
        de.lolhens.jstubber.Stubber.MIXIN.stubDirectory(sourceSets.main.scala.srcDirs[0].toPath(), mixinstubsDir.toPath())
    }
}

compileJava.dependsOn(mixinstubs)

compileJava.doLast {
    delete(compileJava.destinationDir)
    delete(mixinstubsDir)
}

compileScala.doFirst {
    compileScala.options.compilerArgs += compileJava.options.compilerArgs
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
}
```

should I leave this issue open?

**Comment by Mumfrey** [comment]
Honestly it just seems like your project setup is bad. Just put the scala code and the mixins in different sourcesets and wire up the dependencies. It seems like all your pain is being cause by trying to cram everything into `main`.

This isn't really a bug since MG supports mixins in any sourceset and your issue is just poor project layout.
