### ISSUE TITLE
Build which requires this fails.

### ISSUE THREAD

**Issue by NotADinosaur** [SpongePowered/MixinGradle#21]
I'm not 100% sure if this is the right place to put this, but I'm trying to build a program and it fails with the error
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.spongepowered:mixingradle:0.6-SNAPSHOT.
     Required by:
         project :
      > Could not resolve org.spongepowered:mixingradle:0.6-SNAPSHOT.
         > Unable to load Maven meta-data from http://repo.spongepowered.org/maven/org/spongepowered/mixingradle/0.6-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'http://repo.spongepowered.org/maven/org/spongepowered/mixingradle/0.6-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'http://repo.spongepowered.org/maven/org/spongepowered/mixingradle/0.6-SNAPSHOT/maven-metadata.xml'. Received status code 520 from server: Origin Error
Could I get some help?

**Comment by Mumfrey** [comment]
This is not a support forum, this is an issue tracker. Your repo URL has http instead of https and http is no longer supported.
