### ISSUE TITLE
Issue running MixinGrade 0.7-SNAPSHOT 520 Origin Error 

### ISSUE THREAD

**Issue by DiscultDev** [SpongePowered/MixinGradle#22]
Hello,
I notices that the reqest to get the scala-parser-combinators_2.11.jar from http://repo.spongepowered.org/maven/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11 fails with a 520 Origin error.

when Navigating to that link through the browser it works fine, does not work with curl, notices that on the maven for it the url is actually https not http not sure if this is a fix that can be applied to it.

https://pastebin.pl/view/6a5ac4f7

**Comment by DiscultDev** [comment]
this is possible a duplicate for https://github.com/SpongePowered/MixinGradle/issues/21 but it is a different package and version of mixingradle with the error.

**Comment by Mumfrey** [comment]
This is not a support forum, this is an issue tracker. Your repo URL has http instead of https and http is no longer supported.
