### ISSUE TITLE
ForgeGradle 4/Gradle 6.8.1 breaks refmap generation

### ISSUE THREAD

**Issue by Exopandora** [SpongePowered/MixinGradle#23]
I updated my project to ForgeGradle 4 alongside gradle version 4.8.1 and the refmap generation when running `gradlew build` stopped working. When using the recompiled and reobfuscated mod on runtime it crashes the game. Is this a known issue or is there a workaround for this?

build.gradle dependencies:
```
dependencies {
    classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '4.1.+', changing: true
}
```

gradle-wrapper.properties:
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.8.1-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

**Comment by KR33PY** [comment]
Same.

**Comment by 0-x-2-2** [comment]
```groovy
dependencies {
    minecraft \"net.minecraftforge:forge:${FORGE_VERSION}\"
    annotationProcessor \'org.spongepowered:mixin:0.8.2:processor\'
    }
```

**Comment by 0-x-2-2** [comment]
Seems to be still a little messed up if you don't use the main source set but other than that it seems to be working?

**Comment by Exopandora** [comment]
I did my testing with the default build.gradle from forge and applied just the changes from the mixingradle readme. When using fg 3.+ it works just fine. Upon switching to fg 4.1.+ it breaks.

**Comment by Exopandora** [comment]
> 
> 
> ```groovy
> dependencies {
>     minecraft "net.minecraftforge:forge:${FORGE_VERSION}"
>     annotationProcessor 'org.spongepowered:mixin:0.8.2:processor'
> }
> ```

This works but only if i name my refmap file `<sourceset>.refmap.json`

**Comment by Exopandora** [comment]
Regarding the previous comment: This causes no issues for a single mod. But when starting with multiple mods the game crashes.

**Comment by bush-did-711** [comment]
still happening on fg 5
