### ISSUE TITLE
Could not resolve all artifacts for configuration ':classpath'.

### ISSUE THREAD

**Issue by AcaiBerii** [SpongePowered/MixinGradle#24]
Could not find mixingradle.jar (org.spongepowered:mixingradle:0.7-SNAPSHOT).
     Searched in the following locations:
         https://files.minecraftforge.net/maven/org/spongepowered/mixingradle/0.7-SNAPSHOT/mixingradle-0.7-SNAPSHOT.jar

**Comment by gabizou** [comment]
Update your build script repositories since forge updated theirs. This isn't a support forum, you would've had a faster response in discord...
