### ISSUE TITLE
Incompatible with Gradle 7

### ISSUE THREAD

**Issue by PaintNinja** [SpongePowered/MixinGradle#26]
MixinGradle appears to be incompatible with Gradle 7 at the moment. I've tried doing a PR myself however my Gradle plugin dev knowledge is very barebones so I didn't get far.

To reproduce:
1) Download the latest Forge MDK
2) `gradlew wrapper --gradle-version 7.0.2`
3) Change ForgeGradle version to `5.0.1`
4) Apply MixinGradle and the annotationProcessor line as usual
5) `gradlew build`

Stacktrace: https://pastebin.com/raw/YpQTFTGB

**Comment by shartte** [comment]
I believe this is now fixed in the master-branch. At least I am not getting this problem anymore.
