### ISSUE TITLE
Gradle 3.4.1 incompatibility

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/MixinGradle#3]
Attempting to use MixinGradle with a project that uses Gradle 3.4.1 results in the following error.

```
Could not set unknown property 'refMap' for source set 'main' of type org.gradle.api.internal.tasks.DefaultSourceSet.
```

**Comment by Mumfrey** [comment]
As a work-around you should still be able to use the legacy syntax to decorate the sourceSet:

```groovy
mixin {
    add("main", "refmap.name.json")
}
```

I will look into why the metaclass extension isn't working in 3.4.1, the `refMap` member` gets added to the `SourceSet` interface directly so it should in theory just work regardless, no idea how it broke.

**Comment by TonyFoster** [comment]
Same problem here.

**Comment by Mumfrey** [comment]
I'm aware of what causes this, gradle added some dumb internal handling of properties which bypasses groovy's normal handling of properties so I need to find some way to hook into their new system. In the mean time the above solution works, as does accessing the property directly via `ext` as follows:

```groovy
sourceSets {
    main {
        ext.refMap = "mixins.whatever.refmap.json"
    }
}
```

**Comment by Mumfrey** [comment]
Since recent gradle versions just seem to make this usage of groovy language features completely impossible in this case, I'm just going to update the documentation and declare that `ext.refMap` is now the correct way to do this, since the old way doesn't seem possible any more.
