### ISSUE TITLE
Refmap doesn't generate

### ISSUE THREAD

**Issue by AQRRastiq** [SpongePowered/MixinGradle#36]
Hi, I created this issue because when I test my tweaker client created with forgegradle and mixingradle, I get this warning :

`[10:06:12] [main/WARN]: Reference map 'mixins.arkemys.refmap.json' for mixins.arkemys.json could not be read. If this is a development environment you can ignore this message`

Then I get this error : 

`[10:06:12] [main/FATAL]: Mixin apply failed mixins.arkemys.json:client.MixinMinecraft -> ave`

Then my client crashes.

I think it is coming from the fact that my refmap isn't generating. I tried applying many fixes but it didn't solve my problem.

By the way here is my build.gradle :

https://pastebin.com/LF7Fx9bd

**Comment by archie426** [comment]
Have this issue too

**Comment by Mumfrey** [comment]
This is an issue tracker not a support forum. For support questions use discord, though since you're using 1.8.9 your environment is not supported anyway.
