### ISSUE TITLE
Can someone fix this issue?

### ISSUE THREAD

**Issue by GF-Huang** [SpongePowered/MixinGradle#52]
https://github.com/MineDojo/MineDojo/issues/113

Caused by `MixinGradle-dcfaf61.jar` missing.

https://jitpack.io/com/github/SpongePowered/MixinGradle/dcfaf61/MixinGradle-dcfaf61.jar show me **Not found**.

**Comment by ntlm1686** [comment]
Is this solved?

**Comment by GF-Huang** [comment]
> Is this solved?

https://github.com/MineDojo/MineDojo/issues/113 Read all comments.
