### ISSUE TITLE
Javadoc task fails by default with properly documented Overwrites (unknown tag: reason)

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/MixinGradle#7]
I haven't figured out how to workaround it with gradle, but the way to fix it is to add custom tag to javadoc. I think this could be done automatically by mixingradle.

**Comment by JBYoshi** [comment]
Maybe `@reason` could be moved to the main description?

**Comment by Barteks2x** [comment]
I found a way to workaround it with gradle since I reported it:

kotlin-dsl version:
```kotlin
javadoc.apply {
    (options as StandardJavadocDocletOptions).tags = listOf("reason")
}
```

groovy version:
```groovy
javadoc.apply {
    options.tags = [ "reason" ]
}
```
